[defaults]
version_major = 1
version_minor = 1
role = 3
usage = 0
lifecycle = 0
oem_constraint = 0
soc_class = 0
soc_id = "0x00000000000000000000000000000000"
permissions_mask = "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
extensions = ""

[root]
role = 1

[intermediate]
role = 2
soc_class = 0x01020304

[crt1]
soc_id = "0x0a0b0c0d8e1aed96b39286aeb3e4e63b"
permissions_mask = "0x0000000003FFFFFFFFFFFFFF00000000"

[crt2]
soc_id = "0x0a0b0c0d8e1aed96b39286aeb3e4e63b"
permissions_mask = "0x8000000003FFFFFFFFFFFFFF00000000"

[crt3]
soc_id = "0x0a0b0c0d8e1aed96b39286aeb3e4e63b"
usage = 2
permissions_mask = "0x00000000000000000000000000000000"
